export const data = [
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean pulvinar viverra nisi. Mauris purus neque, varius non mauris at, convallis interdum urna. Phasellus commodo nisl erat, vitae gravida leo mollis sit amet. Sed vel ullamcorper tellus. Mauris nunc diam, varius et ultrices quis, faucibus eget leo. Pellentesque et sem ipsum. Nullam ac bibendum orci, eget sollicitudin neque. Suspendisse feugiat et elit id fermentum. Nam nec posuere purus. Cras convallis enim ante, eu facilisis magna fermentum at. Sed tortor lacus, efficitur vehicula cursus eget, sodales eget ipsum. Pellentesque fringilla eget metus vitae varius. Donec venenatis quam nec lacinia ornare. Ut sit amet eros enim. Nullam quis dolor vitae orci porttitor varius eget eget felis. Sed tempus feugiat turpis.",
  "Nam magna sapien, pharetra a tellus vel, ultricies porta dui. Integer id ipsum tincidunt mauris ornare pellentesque. Nunc eget tellus mattis, volutpat quam id, fringilla nunc. Aliquam euismod, magna vel vulputate hendrerit, dolor diam tempor est, sit amet finibus mi augue semper lorem. Mauris elementum erat auctor enim feugiat scelerisque. Nunc euismod finibus tortor nec aliquam. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam justo nibh, porttitor vel ultrices eu, condimentum non nisi. In eleifend odio augue, ut pretium ligula malesuada vitae. Nunc consequat efficitur diam nec sollicitudin.",
  "Sed et posuere erat, nec gravida purus. Aenean non suscipit eros. Praesent id congue magna, eleifend tempor purus. In suscipit diam nibh, ut blandit lorem euismod sed. Pellentesque sagittis mollis tortor. Donec placerat mattis vehicula. Quisque id nunc nibh. Aliquam malesuada nec nisl imperdiet euismod. Vestibulum non posuere purus, scelerisque semper lorem. In fringilla metus id fringilla efficitur. Sed dapibus lacinia felis, nec vehicula lacus gravida ut. Fusce justo lectus, maximus quis convallis et, congue vel libero. Nulla eu augue euismod, posuere purus vitae, tempus dui. Donec tristique vel felis et vestibulum. In pulvinar risus sed metus consequat varius.",
  "Proin quis lectus nec magna pellentesque interdum id ac est. Aliquam velit leo, placerat et sagittis sed, sodales sit amet massa. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Suspendisse rhoncus sapien a est ullamcorper, et bibendum lacus vulputate. Morbi pellentesque bibendum neque, vitae tristique ex scelerisque eget. Cras sollicitudin risus at odio cursus aliquet. Sed non sollicitudin tortor, at tempus velit. Morbi id nunc vitae est interdum hendrerit vitae id dui. Sed accumsan in enim eget pretium. Quisque quis consectetur ipsum. Quisque a pulvinar felis.",
  "Curabitur ligula tellus, molestie sit amet mi a, rutrum pulvinar massa. Praesent nec erat leo. Nullam ut magna at mi tempus rutrum. Curabitur laoreet eros vel mauris lacinia tristique. Fusce lobortis, lorem finibus feugiat posuere, nunc risus sollicitudin mauris, id mollis odio massa eu ipsum. Praesent diam massa, aliquet ut auctor eleifend, interdum eget est. Donec condimentum aliquet convallis. Suspendisse pharetra vestibulum molestie. Sed egestas turpis nisi, quis fermentum nunc vestibulum laoreet. Vestibulum et turpis dapibus, lacinia ipsum rutrum, iaculis dolor. Donec varius placerat metus a rhoncus. Vivamus vitae condimentum tortor. Duis dapibus neque non urna porta efficitur. Nulla hendrerit tristique erat, a accumsan orci commodo ac. Praesent quis erat eros. Sed eget bibendum eros.",
  "In porta, odio sit amet sodales lobortis, magna dolor fermentum felis, in consequat orci risus vitae turpis. Proin at ligula tortor. In vitae erat quis nisi vehicula aliquam quis vel diam. Vivamus vitae luctus ex, a fringilla tortor. Integer et sodales augue. Donec mollis feugiat leo eget tempus. Phasellus feugiat tortor dui, vitae pellentesque augue euismod a. Donec vulputate sagittis urna, sit amet efficitur lacus bibendum eget. Donec sit amet ipsum nisi. Nam pellentesque accumsan ante ac dapibus. Donec luctus mauris id felis tempus fringilla vitae at mauris. Morbi lobortis lacus hendrerit lacus vehicula tincidunt. Mauris luctus nunc a tellus rhoncus blandit. Quisque pharetra quam tortor, vel hendrerit felis viverra in.",
  "Nulla facilisi. Proin vestibulum ex vitae lacus iaculis elementum. Nam volutpat mattis mauris, vitae consectetur lectus molestie quis. Nullam ac bibendum metus. Aliquam eu hendrerit leo. Nullam rutrum lacus sit amet arcu tincidunt pellentesque. Cras malesuada suscipit orci. Vestibulum interdum urna urna, eu venenatis tellus tristique et.",
  "Aenean felis purus, lobortis vel egestas non, interdum eget sapien. Maecenas molestie feugiat elit. Nam nec lorem urna. Suspendisse potenti. Cras vel ante quis nisi mattis cursus ut in diam. Aliquam hendrerit facilisis nibh bibendum congue. Nam augue urna, sagittis eget ultricies vel, porta at dui. Vivamus nec nisl nec arcu gravida pretium. Vivamus non bibendum erat, non ultricies ante.",
];
